# Generated by Django 2.2.2 on 2021-01-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('custemer_address', models.CharField(max_length=200)),
                ('customer_detail', models.CharField(max_length=200)),
                ('product_user', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='customer_qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('first_value', models.CharField(max_length=100)),
                ('last_value', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
                ('history_owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_head', models.CharField(max_length=100)),
                ('note_body', models.TextField()),
                ('note_user', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.CharField(max_length=100)),
                ('product_head', models.CharField(max_length=100)),
                ('product_body', models.TextField()),
                ('product_user', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField(default=0)),
                ('date_time', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='product_qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehose_name', models.CharField(max_length=100)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('owener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
